### ISSUE TITLE
NoSuchMethodError : java.lang.String.isBlank()Z @ de.xxschrandxx.bca.core.SQLHandler:688

### ISSUE THREAD

**Issue by VozDeOuro** [xXSchrandXx/BungeeCordAuthenticator#1]
hello i'm getting this error when trying to login
NoSuchMethodError : java.lang.String.isBlank()Z @ de.xxschrandxx.bca.core.SQLHandler:688
![image](https://user-images.githubusercontent.com/36045463/113782481-a3e29480-9708-11eb-9de4-28defd5fbcab.png)

**Comment by xXSchrandXx** [comment]
You need to use Java 11 with BungeeCordAuthenticator. Source: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#isBlank()

**Comment by VozDeOuro** [comment]
with java 11 i'm getting this one when i connect to the server 

> `[09:41:39 WARN] [BungeeCordAuthenticatorBungee]: SQLHandler.getType | returns null.
> [09:41:39 WARN]: Error dispatching event PostLoginEvent(player=VozDeOuro) to listener de.xxschrandxx.bca.bungee.listener.BCABListener@23811a09
> java.lang.NullPointerException: null
>         at de.xxschrandxx.bca.bungee.listener.BCABListener.onPostLogin(BCABListener.java:41) ~[?:?]
>         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
>         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
>         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
>         at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
>         at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
>         at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
>         at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:453) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
>         at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:555) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
>         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
>         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
>         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
>         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
>         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
>         at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by xXSchrandXx** [comment]
Wich version of BungeeCordAuthenticator do you use?
Did you modify the database?
Did an error happen while registering the user VozDeOuro (Creating entry in the database)?

If nothing else went wrong, 
Does this happen again if you reset the player with `/bcab forcereset VozDeOuro`?

**Comment by VozDeOuro** [comment]
_i'm using the version_ = **BungeeCordAuthenticator-0.0.3-SNAPSHOT**
_Did you modify the database?_ = **No**
_Did an error happen while registering the user VozDeOuro (Creating entry in the database)?_ = **i'm using fastlogin 
didn't see any change on database.**

plugin list:
![image](https://user-images.githubusercontent.com/36045463/113875992-ac30e300-978d-11eb-8116-8b9c3b1594f4.png)

**Comment by xXSchrandXx** [comment]
Please re download [0.0.3-SNAPSHOT](https://maven.gamestrike.de/docs/BungeeCordAuthenticator/0.0.3-SNAPSHOT/BungeeCordAuthenticator-0.0.3-SNAPSHOT.jar) and try again.

**Comment by VozDeOuro** [comment]
> 
> 
> Please re download [0.0.3-SNAPSHOT](https://maven.gamestrike.de/docs/BungeeCordAuthenticator/0.0.3-SNAPSHOT/BungeeCordAuthenticator-0.0.3-SNAPSHOT.jar) and try again.

thats fixed it :) thx.  
now is just getting a WARN 

> [11:36:25 WARN] [BungeeCordAuthenticatorBungee]: SQLHandler.getVersion | returns null.


i have 1 question when i log in on the server the plugin don't say nothing like "please register using ..." thats correct ?

**Comment by xXSchrandXx** [comment]
> i have 1 question when i log in on the server the plugin don't say nothing like "please register using ..." thats correct ?

At the moment there are no "Please login with ..." or Please Register with ..." messages.
But I could add them with the new version.

Only if the player tries to do not-allowed stuff (set in the configs), it does tell him, that he needs to login / register.

**Comment by xXSchrandXx** [comment]
> now is just getting a WARN

If you re-authenticate, does it warn you again or does the version fix work?

**Comment by VozDeOuro** [comment]
> At the moment there are no "Please login with ..." or Please Register with ..." messages.
> But I could add them with the new version.

that would be awesome


> If you re-authenticate, does it warn you again or does the version fix work?

this fix works thx 
stop showing it
